---
title: "model_building"
author: "Jiho Kwak, 2020-17530"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(showtext)

# 한글 폰트 추가 (구글 Noto Sans KR)
font_add_google("Noto Sans KR", "noto")
showtext_auto()
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r, message=FALSE}
library(INLA)
library(data.table)
library(dplyr)
library(stringr)
library(sf)
library(spdep)
library(Matrix)
```


## File Import

### dt_q
```{r}
path_q <- "dt_q_mod.csv"
dt_q <- read.csv(
  path_q,
  fileEncoding = "euc-kr",   # 파일이 euc-kr로 저장됨
  stringsAsFactors = FALSE
)
setDT(dt_q)
```

### dt_y
```{r}
path_y <- "dt_y_mod.csv"
dt_y <- read.csv(
  path_y,
  fileEncoding = "euc-kr",
  stringsAsFactors = FALSE
)
setDT(dt_y)
```

### sgg(merged) shapefile
```{r}
# # 1) 읽기
# sgg <- st_read("sgis_sgg_merged/SGG_merged.gpkg", quiet = TRUE)
# 
# # 2) 좌표계: 라벨 없으면 set_crs, 있으면 transform (5186 고정)
# crs_now <- st_crs(sgg)
# if (is.na(crs_now)) {
#   sgg <- st_set_crs(sgg, 5186)
# } else if (is.na(crs_now$epsg) || crs_now$epsg != 5186) {
#   sgg <- st_transform(sgg, 5186)
# }
# sgg <- st_make_valid(sgg)
# 
# sgg <- sgg |>
#   arrange(new_sigungu_cd) |>
#   mutate(idx = row_number())
```

### Graph
```{r}
G <- INLA::inla.read.graph("sgg_graph.adj")
```


## Quarterly

### RW1_null

```{r}
dt_q$e9_f <- dt_q$e9 + 1L
dt_q$E_e9 <- dt_q$population_total * (sum(dt_q$e9) / sum(dt_q$population_total))
dt_q$RR <- dt_q$e9 / dt_q$E_e9

fit_baseline_q <- inla(
  e9_f ~ #1 + #offset(log(population_total)) + 
  f(time_id, model = "ar1",# scale.model = TRUE,
             hyper = list(prec = list(prior = "pc.prec", param = c(1, 0.01)))),
  data = dt_q,
  family = "poisson",
  E = dt_q$E_e9,
  # offset = log(dt_q$population_total),   # ← 여기!
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                            improved.simplified.laplace = TRUE,
                           control.vb = list(strategy = "mean")),
  verbose = TRUE
)

summary(fit_baseline_q)

```

```{r}
fit_baseline_q <- inla(
  RR ~ 1 + #offset(log(population_total)) + 
  f(time_id, model = "ar1",# scale.model = TRUE,
             hyper = list(prec = list(prior = "pc.prec", param = c(1, 0.01)))),
  data = dt_q,
  family = "lognormal",
  # E = dt_q$E_e9,
  # offset = log(dt_q$population_total),   # ← 여기!
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                            improved.simplified.laplace = TRUE,
                           control.vb = list(strategy = "mean")),
  verbose = TRUE
)

summary(fit_baseline_q)


```

### RW1

```{r}
# 0) 공변량 생성 (음수/NA 방지)
dt_q <- dt_q %>%
  mutate(
    lnx   = log1p(pmax(trade_export_val, 0)),
    lnm   = log1p(pmax(trade_import_val, 0)),
    balzs = as.numeric(scale(trade_balance))
  )

# 1) 노출량 E = 인구 (이미 있다면 생략)
dt_q <- dt_q %>% mutate(E_pop = as.numeric(population_total))
# 논리 불일치 정리(권장): E=0 & e9>0 제거
dt_q <- dt_q %>% filter(!(E_pop <= 0 & e9 > 0))

# 2) (중요) 공식(formula)을 명시적으로 따로 보관
form_baseline_q <- e9 ~ 1 + offset(log(population_total)) + 
  f(time_id, model="ar1", #scale.model=TRUE,
    hyper=list(prec=list(prior="pc.prec", param=c(0.01,0.01))))

# 3) 공변량 추가한 공식
form_rw1cov_q <- update(form_baseline_q, . ~ . + 
                       trade_balance_z +
                       mig_total_out_z +
                       # grdp_1st_z +
                       # grdp_2nd_z +
                       # grdp_3rd_z +
                       ind_ratio_manufacturing_z +
                       ind_ratio_construction_z +
                       ind_ratio_wholesale_retail_z +
                       lf_employment_rate_15_64 +
                       dummy_covid +
                       dummy_capital +
                      #  dummy_si +
                       dummy_gun
)

# 4) 적합 (E= 방식; offset 쓰지 않음)
fit_rw1cov_q <- inla(
  formula = form_rw1cov_q,
  data    = dt_q,
  family  = "poisson",
  # offset       = log(dt_q$population_total), #dt_q$E_pop,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           improved.simplified.laplace = TRUE,
                           control.vb=list(emergency=50)),
  verbose = TRUE
)


library(tidycensuskr)
data(adm2_sf_2020)
adm2 <- adm2_sf_2020
adm2 <- sf::st_read("/home/felix/Documents/admsgg_simp.gpkg") |>
  dplyr::mutate(sggcd = as.integer(ifelse(substr(LEGLCD_SE, 1, 4) == "4811", "48110", substr(LEGLCD_SE, 1, 5)))) |>
  dplyr::group_by(sggcd) |>
  dplyr::summarize() |>
  dplyr::ungroup()
sf::st_crs(adm2) <- "EPSG:5179"

tinyplot::plt(
  x = as.integer(as.factor(dt_q$yyyymm)), y = dt_q$e9_f,
  by = dt_q$sgg_code10, type = "l",
  data = dt_q
)


adm2x <-
  adm2 |>
  dplyr::left_join(
    dt_q |>
      dplyr::filter(year == 2021, quarter == 4) |>
      dplyr::select(sgg_code10, e9_f) |>
      dplyr::distinct(),
    by = c("sggcd" = "sgg_code10")
  )
plot(adm2x[, "e9_f"])

dt_q |>
  dplyr::filter(canon_sigungu_name == "창원시") |>
  dplyr::select(sgg_code10)

summary(fit_rw1cov_q)
fit_rw1cov_q$waic$waic; fit_rw1cov_q$dic$dic
```

### AR1_null

```{r}
form_ar1 <- e9 ~ 1 + offset(log(population_total)) + 
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.8, 0.5))     # AR(1) 상관 PC prior
    )
  )


form_ar1_rr <- e9_f ~ 1 +
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.8, 0.5))     # AR(1) 상관 PC prior
    )
  )


fit_ar1 <- inla(
  formula = form_ar1,
  data    = dt_q,
  family  = "poisson",
  # offset       = dt_q$E_pop,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           control.vb=list(emergency=50))
)

summary(fit_ar1)
fit_ar1$waic$waic; fit_ar1$dic$dic
```

### AR1

```{r}
# 3) 공변량 추가한 공식
form_ar1cov_q <- update(form_ar1_rr, . ~ . + lnx + lnm + balzs)

options(inla.mode = "experimental")

# 4) 적합 (E= 방식; offset 쓰지 않음)
fit_ar1cov_q_rr <- inla(
  formula = form_ar1cov_q,
  data    = dt_q,
  family  = "poisson",
  E       = dt_q$E_e9,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
  improved.simplified.laplace = TRUE,
                           control.vb=list(emergency=50)),
  verbose = TRUE
)

pairs(dt_q[, c("e9_f", "E_e9", "lnx", "lnm", "balzs")])


summary(fit_ar1cov_q_rr)
fit_ar1cov_q$waic$waic; fit_ar1cov_q$dic$dic
```

### BYM2 + AR

```{r}
# BYM2: 공간, 그래프=G
# AR(1): 시간
form_bym2_ar1 <- e9 ~ 1 + offset(log(population_total)) + 
  f(space_id, model="bym2", graph=G,
    scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),     # precision PC prior
      phi  = list(prior="pc", param=c(0.5, 0.5))          # mixing parameter prior
    )
  ) +
  f(time_id, model="ar1",
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))     # AR(1) 상관 PC prior
    )
  )

fit_bym2_ar1 <- inla(
  formula = form_bym2_ar1,
  data    = dt_q,
  family  = "poisson",
  # E       = dt_q$E_pop,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link = 1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
  improved.simplified.laplace = TRUE,
                           control.vb=list(emergency=50)),
  verbose = TRUE
)

summary(fit_bym2_ar1)
fit_bym2_ar1$waic$waic; fit_bym2_ar1$dic$dic

```

### BYM2 \* AR (time-varying spatial random effects)

```{r}
# 공간 ID를 시간별로 복제한 인덱스(상호작용용)
dt_q <- dt_q %>% arrange(time_id, space_id)
dt_q$space_id_st <- dt_q$space_id          # 동일 값이지만 group=time_id로 복제될 것

form_interaction <- e9 ~ 1 + offset(log(population_total)) + 
  # # 메인 공간효과(선택): 때로는 제거하고 상호작용만 두기도 함
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  # 메인 시간효과
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  # 공간×시간 상호작용: BYM2를 시간별 복제, 시간 간 AR(1)로 연결
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(model="ar1",
                         hyper = list(
                           theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                           rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
                         )),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

fit_interaction <- inla(
  formula = form_interaction,
  data    = dt_q,
  family  = "poisson",
  # E       = dt_q$E_pop,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           improved.simplified.laplace = TRUE,
                           control.vb=list(emergency=50)),
  verbose = TRUE
)

summary(fit_interaction)
fit_interaction$waic$waic; fit_interaction$dic$dic

```


### BYM2 \* AR + cov

```{r}
form_interaction <- e9 ~ 1 +offset(log(population_total)) + 
  # # 메인 공간효과(선택): 때로는 제거하고 상호작용만 두기도 함
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  # 메인 시간효과
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  # 공간×시간 상호작용: BYM2를 시간별 복제, 시간 간 AR(1)로 연결
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(model="ar1",
                         hyper = list(
                           theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                           rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
                         )),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

# 3) 공변량 추가한 공식
form_cov_q <- update(form_interaction, . ~ . + 
                       trade_export_val_z +
                       ind_ratio_manufacturing_z +
                       mig_net_z +
                       sido_lf_unemployment_rate_z +
                       sido_num_shortage_z
                     )

# 4) 적합 (E= 방식; offset 쓰지 않음)
fit_cov_q <- inla(
  formula = form_cov_q,
  data    = dt_q,
  family  = "poisson",
  # E       = dt_q$population,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                            improved.simplified.laplace = TRUE,
                           int.strategy = "auto",
                           control.vb=list(emergency=50)),
  verbose = TRUE
)
# crashed
summary(fit_cov_q)
fit_cov_q$waic$waic; fit_cov_q$dic$dic
```

### BYM2 \* AR after Spatial +

```{r}
# 패키지 로드 -------------------------------------------------------------
library(INLA)
library(dplyr)

# 0. 데이터 전처리: 정렬 + 공변량 생성 -----------------------------------
# dt_q: 시공간 패널 (열: e9, E_pop, trade_export_val, trade_import_val, time_id, space_id 등)

dt_q <- dt_q %>%
  arrange(time_id, space_id) %>%
  mutate(
    # 시공간 상호작용용 공간 인덱스 (time_id로 group 복제)
    space_id_st = space_id,
    # 무역 공변량 (원본)
    lnx   = log1p(pmax(trade_export_val, 0)),   # export
    lnm   = log1p(pmax(trade_import_val, 0)),   # import
    balzs = as.numeric(scale(trade_balance))    # 필요하면 나중에 사용
  )

# (선택) NA 제거가 필요하면 여기서 처리:
# dt_q <- dt_q %>% filter(!is.na(lnx), !is.na(lnm))


# 1. Spatial+용 보조 모형: lnx ~ BYM2 × AR(1) (Gaussian) -----------------
form_lnx_spplus <- lnx ~ 1 +
  # 시간 AR(1)
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  # 공간×시간 BYM2 * AR(1)
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(
      model="ar1",
      hyper = list(
        theta1 = list(prior="pc.prec", param=c(1, 0.01)),
        rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
      )
    ),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

fit_lnx_spplus <- inla(
  formula = form_lnx_spplus,
  data    = dt_q,
  family  = "gaussian",
  control.compute = list(config = TRUE),
  control.inla = list(strategy = "simplified.laplace",
                      control.vb = list(emergency = 50))
)

# Spatial+용 공변량: lnx에서 시공간 패턴(fitted)을 제거 -------------------
dt_q$lnx_fit  <- fit_lnx_spplus$summary.fitted.values[, "mean"]
dt_q$lnx_sppl <- dt_q$lnx - dt_q$lnx_fit
dt_q$lnx_sppl <- as.numeric(scale(dt_q$lnx_sppl))   # 스케일링 (선택)


# 2. Spatial+용 보조 모형: lnm ~ BYM2 × AR(1) (Gaussian) -----------------
form_lnm_spplus <- lnm ~ 1 +
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(
      model="ar1",
      hyper = list(
        theta1 = list(prior="pc.prec", param=c(1, 0.01)),
        rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
      )
    ),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

fit_lnm_spplus <- inla(
  formula = form_lnm_spplus,
  data    = dt_q,
  family  = "gaussian",
  control.compute = list(config = TRUE),
  control.inla = list(strategy = "simplified.laplace",
                      control.vb = list(emergency = 50))
)

# Spatial+용 공변량: lnm에서 시공간 패턴(fitted)을 제거 -------------------
dt_q$lnm_fit  <- fit_lnm_spplus$summary.fitted.values[, "mean"]
dt_q$lnm_sppl <- dt_q$lnm - dt_q$lnm_fit
dt_q$lnm_sppl <- as.numeric(scale(dt_q$lnm_sppl))   # 스케일링 (선택)


# 3. 원래 BYM2 × AR(1) E9 모형 (공변량 없이) ------------------------------
form_interaction <- e9 ~ 1 +
  # (선택) 메인 공간효과: 필요시 주석 해제
  # f(space_id, model="bym2", graph=G, scale.model=TRUE,
  #   hyper = list(
  #     prec = list(prior="pc.prec", param=c(1, 0.01)),
  #     phi  = list(prior="pc", param=c(0.5, 0.5))
  #   )) +
  # 시간 AR(1)
  f(time_id, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  # 공간×시간 상호작용 BYM2 * AR(1)
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(
      model="ar1",
      hyper = list(
        theta1 = list(prior="pc.prec", param=c(1, 0.01)),
        rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
      )
    ),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

fit_interaction <- inla(
  formula = form_interaction,
  data    = dt_q,
  family  = "poisson",
  E       = dt_q$E_pop,   # 기대노출(인구)
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           control.vb=list(emergency=50))
)

fit_interaction$waic$waic
fit_interaction$dic$dic
summary(fit_interaction)


# 4. Spatial+ 공변량을 넣은 최종 E9 모형 -------------------------------
# 원래 form_interaction에 lnx, lnm 대신 lnx_sppl, lnm_sppl 추가
form_cov_q_sppl <- update(
  form_interaction,
  . ~ . + lnx_sppl + lnm_sppl
)

fit_cov_q_sppl <- inla(
  formula = form_cov_q_sppl,
  data    = dt_q,
  family  = "poisson",
  E       = dt_q$E_pop,
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           control.vb=list(emergency=50))
)

fit_cov_q_sppl$waic$waic
fit_cov_q_sppl$dic$dic
summary(fit_cov_q_sppl)

# (선택) 원래 공변량 버전과 비교하고 싶으면:
# form_cov_q <- update(form_interaction, . ~ . + lnx + lnm)
# fit_cov_q  <- inla(... 동일 옵션 ...)
# 그리고 fit_cov_q vs fit_cov_q_sppl의 β, WAIC, DIC 비교

```

### BYM2 \* RW

```{r}
# 공간 ID를 시간별로 복제한 인덱스(상호작용용)
dt_q <- dt_q %>% arrange(time_id, space_id)
dt_q$space_id_st <- dt_q$space_id          # 동일 값이지만 group=time_id로 복제될 것

form_interaction_rw <- e9 ~ 1 +
  # 메인 공간효과(선택): 때로는 제거하고 상호작용만 두기도 함
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  # 메인 시간효과
  f(time_id, model="rw1",
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      )) +
  # 공간×시간 상호작용: BYM2를 시간별 복제, 시간 간 RW(1)로 연결
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id,
    control.group = list(model="rw1",
                         hyper = list(
                           prec = list(prior="pc.prec", param=c(1, 0.01)),
                         )),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
    )
  )

fit_interaction_rw <- inla(
  formula = form_interaction_rw,
  data    = dt_q,
  family  = "poisson",
  E       = dt_q$E_pop,   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           int.strategy = "auto",
                           control.vb=list(emergency=50))
)

summary(fit_interaction_rw)
fit_interaction_rw$waic$waic; fit_interaction_rw$dic$dic

```

### Model Comparison

```{r}
data.frame(
  model = c("baseline_rw1", "baseline_ar1", "rw1+cov", "bym2_ar1","interaction","bym2_ar1+cov"),
  WAIC  = c(fit_baseline_q$waic$waic,
            fit_ar1$waic$waic,
            fit_rw1cov_q$waic$waic,
            fit_bym2_ar1$waic$waic,
            fit_interaction$waic$waic,
            fit_cov_q$waic$waic),
  DIC   = c(fit_baseline_q$dic$dic,
            fit_ar1$dic$dic,
            fit_rw1cov_q$dic$dic,
            fit_bym2_ar1$dic$dic,
            fit_interaction$dic$dic,
            fit_cov_q$dic$dic)
)

# PIT/요약
hist(fit_bym2_ar1$cpo$pit, breaks=30, main="PIT (BYM2+AR1)")
```

```{r}
dt_y <- dt_y %>%
  mutate(sex_ratio = as.numeric(100 * (population_male / population_female)))
```

```{r}
dt_y <- dt_y %>%
  filter(year <= 2021) %>%
  arrange(canon_group_id, date)
```


## yearly
```{r}
form_interaction_y <- e9 ~ 1 +
  # # 메인 공간효과(선택): 때로는 제거하고 상호작용만 두기도 함
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  # 메인 시간효과
  f(time_id_year, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) #+
  # 공간×시간 상호작용: BYM2를 시간별 복제, 시간 간 AR(1)로 연결
  # f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
  #   group = time_id_year,
  #   control.group = list(model="ar1",
  #                        hyper = list(
  #                          theta1 = list(prior="pc.prec", param=c(1, 0.01)),
  #                          rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
  #                        )),
  #   hyper = list(
  #     prec = list(prior="pc.prec", param=c(1, 0.01)),
  #     phi  = list(prior="pc", param=c(0.5, 0.5))
  #   )
  # )

dt_y <- dt_y |>
  dplyr::mutate(
    trade_balance_1m = trade_balance / 1e6 # original in 1000s
  )
# 3) 공변량 추가한 공식
form_cov_y <- update(form_interaction_y, . ~ . +
                       sex_ratio +
                      # pop_65plus +
                      #  trade_balance +
                      #  mig_total_out +
                       # grdp_1st_z +
                       # grdp_2nd_z +
                       # grdp_3rd_z +
                       ind_ratio_manufacturing +
                       ind_ratio_construction +
                       ind_ratio_wholesale_retail +
                       lf_employment_rate_15_64 +
                       dummy_covid +
                       dummy_capital +
                      # dummy_si +
                       dummy_gun
                     )

dt_y$E_e9 <- dt_y$population_total * (sum(dt_y$e9) / sum(dt_y$population_total))

# 4) 적합 (E= 방식; offset 쓰지 않음)
fit_cov_y <- inla(
  formula = form_cov_y,
  data    = dt_y,
  family  = "poisson",
  E      = dt_y$E_e9,
  # offset       = log(dt_y$population_total),   # ★ 인구를 기대노출로
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           int.strategy = "auto",
                           control.vb=list(emergency=50)),
  verbose = TRUE
)

summary(fit_cov_y)
fit_cov_y$waic$waic; fit_cov_y$dic$dic
```
## Prediction
### lagged cov.
```{r}
library(dplyr)

dt_y <- dt_y %>% 
  arrange(space_id, year) %>%         # 1) 지역별·연도순 정렬
  group_by(space_id) %>%              # 2) 시군구별로 묶고
  mutate(
    sex_ratio_l1         = lag(sex_ratio_z,         1),
    pop_65plus_l1        = lag(pop_65plus_z,       1),
    trade_balance_l1     = lag(trade_balance_z,    1),
    mig_total_out_l1     = lag(mig_total_out_z,    1),
    ind_manuf_l1         = lag(ind_ratio_manufacturing_z, 1),
    ind_constr_l1        = lag(ind_ratio_construction_z,  1),
    ind_wholesale_l1     = lag(ind_ratio_wholesale_retail_z, 1),
    lf_emp_15_64_l1      = lag(lf_employment_rate_15_64, 1)
  ) %>% 
  ungroup()

```


### test

```{r}
# 1) 마스킹 구간 정의
mask_year <- 2023:2025

# 2) 응답 변수 새로 하나 만들어서, 마스킹 연도는 NA로 처리
dt_y$e9_obs <- dt_y$e9
dt_y$e9_obs[dt_y$year %in% mask_year] <- NA


# 3) 모델 적합 (학습 구간만 사용)
form_interaction_y <- e9_obs ~ 1 +
  # # 메인 공간효과(선택): 때로는 제거하고 상호작용만 두기도 함
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  # 메인 시간효과
  f(time_id_year, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    )) +
  # 공간×시간 상호작용: BYM2를 시간별 복제, 시간 간 AR(1)로 연결
  f(space_id_st, model="bym2", graph=G, scale.model=TRUE,
    group = time_id_year,
    control.group = list(model="ar1",
                         hyper = list(
                           theta1 = list(prior="pc.prec", param=c(1, 0.01)),
                           rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
                         )),
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )
  )

# 3) 공변량 추가한 공식
form_cov_y_lag <- update(
  form_interaction_y, 
  . ~ . +
    sex_ratio_l1 +
    pop_65plus_l1 +
    trade_balance_l1 +
    mig_total_out_l1 +
    ind_manuf_l1 +
    ind_constr_l1 +
    ind_wholesale_l1 +
    lf_emp_15_64_l1 +
    # dummy_covid +
    dummy_capital +
    dummy_si +
    dummy_gun
)


fit_cov_y_lag_mask <- inla(
  formula = form_cov_y_lag,
  data    = dt_y,
  family  = "poisson",
  E       = dt_y$population_total,
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(link = 1, compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                           int.strategy = "auto",
                           control.vb = list(emergency = 50))
)


# 마스킹 연도 인덱스
idx_test <- which(dt_y$year %in% mask_year)

# λ_hat: 포아송 평균 μ = E * exp(η) (결과가 이미 Expectation 스케일)
lambda_hat <- fit_cov_y_lag_mask$summary.fitted.values$mean[idx_test]

# 관측값 (원래 e9)
observed <- dt_y$e9[idx_test]
rmse <- sqrt(mean((observed - lambda_hat)^2, na.rm = TRUE))
rmse

```

```{r}
# 1) 마스킹 구간 정의
mask_year <- 2023:2025

# 2) 응답 변수 새로 하나 만들어서, 마스킹 연도는 NA로 처리
dt_y$e9_obs <- dt_y$e9
dt_y$e9_obs[dt_y$year %in% mask_year] <- NA


# 3) 모델 적합 (학습 구간만 사용)
form_y_ar1_nocov <- e9_obs ~ 1 +
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  f(time_id_year, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    ))

fit_nocov_y_mask <- inla(
  formula = form_y_ar1_nocov,      # 기존 연도별 BYM2+AR1+공변량 모델
  data    = dt_y,
  family  = "poisson",
  E       = dt_y$population_total,
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(link = 1, compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                           int.strategy = "auto",
                           control.vb = list(emergency = 50)),
  verbose = FALSE
)

# 마스킹 연도 인덱스
idx_test <- which(dt_y$year %in% mask_year)

# λ_hat: 포아송 평균 μ = E * exp(η) (결과가 이미 Expectation 스케일)
lambda_hat <- fit_nocov_y_mask$summary.fitted.values$mean[idx_test]

# 관측값 (원래 e9)
observed <- dt_y$e9[idx_test]

rmse <- sqrt(mean((observed - lambda_hat)^2, na.rm = TRUE))
rmse
```

```{r}
# 테스트 연도에서의 차이 요약
summary(lambda_cov[idx_test] - lambda_nocov[idx_test])

# 최대 차이
max_diff <- max(abs(lambda_cov[idx_test] - lambda_nocov[idx_test]))
max_diff

head(cbind(
  cov   = lambda_cov[idx_test],
  nocov = lambda_nocov[idx_test]
))

```
```{r}
options(digits = 10)

observed <- dt_y$e9[idx_test]

rmse_cov   <- sqrt(mean((observed - lambda_cov[idx_test])^2,   na.rm = TRUE))
rmse_nocov <- sqrt(mean((observed - lambda_nocov[idx_test])^2, na.rm = TRUE))

rmse_cov
rmse_nocov
```
```{r}
summary(fit_cov_y_mask)$fixed
```

### yearly 대안 모형 예시

```{r}
# 0) OLS/공간회귀용 비율 변수
dt_y_yearly <- dt_y %>%
  mutate(
    e9_rate = (e9 / population_total) * 1e5,  # 인구 10만 명당 비율
    log_rate = log1p(e9_rate)
  )

# 1) Simple OLS (연도 고정효과 포함)
ols_yearly <- lm(
  log_rate ~ sex_ratio + pop_65plus_z + trade_balance_z + factor(year),
  data = dt_y_yearly
)
summary(ols_yearly)

# 2) Spatial lag model (SAR) on 로그 비율
W_mat  <- INLA:::inla.graph2matrix(G)                 # INLA 그래프 → 인접행렬
listw  <- spdep::mat2listw(as.matrix(W_mat), style="W")
sar_fit <- spatialreg::lagsarlm(
  log_rate ~ sex_ratio + pop_65plus_z + trade_balance_z,
  data  = dt_y_yearly,
  listw = listw,
  method = "eigen"
)
summary(sar_fit)

# 3) Bayesian Poisson (공변량 없이) + BYM2 + AR1
form_y_ar1_nocov <- e9 ~ 1 +
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  f(time_id_year, model="ar1",
    hyper = list(
      theta1 = list(prior="pc.prec", param=c(1, 0.01)),
      rho  = list(prior="pc.cor1", param=c(0.7, 0.5))
    ))

fit_y_ar1_nocov <- inla(
  formula = form_y_ar1_nocov,
  data    = dt_y,
  family  = "poisson",
  E       = dt_y$population_total,
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           int.strategy = "auto",
                           control.vb=list(emergency=50))
)

# 4) Bayesian Poisson (공변량 없이) + BYM2 + RW1
form_y_rw1_nocov <- e9 ~ 1 +
  f(space_id, model="bym2", graph=G, scale.model=TRUE,
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01)),
      phi  = list(prior="pc", param=c(0.5, 0.5))
    )) +
  f(time_id_year, model="rw1",
    hyper = list(
      prec = list(prior="pc.prec", param=c(1, 0.01))
    ))

fit_y_rw1_nocov <- inla(
  formula = form_y_rw1_nocov,
  data    = dt_y,
  family  = "poisson",
  E       = dt_y$population_total,
  control.compute   = list(dic=TRUE, waic=TRUE, cpo=TRUE),
  control.predictor = list(link=1, compute=TRUE),
  control.inla      = list(strategy="simplified.laplace",
                           int.strategy = "auto",
                           control.vb=list(emergency=50))
)
```
## Prediction
```{r}
# 연도별 hold-out 예측 비교 (예: 2023–2024 마스킹)
# data.table을 쓸 때는 괄호를 반드시 넣어 `!(year %in% ...)` 형태로
# 작성해야 lubridate::year() 등과 충돌하지 않고 "'match' requires vector arguments"
# 오류를 피할 수 있습니다.
mask_years <- 2023:2024

# 0) 공통 데이터 준비
# data.table 스타일로 바로 train/test를 나눌 경우 예시
# (괄호를 써서 `!(year %in% mask_years)` 형태로 지정)
# dt_y_dt   <- as.data.table(dt_y)
# dt_train  <- dt_y_dt[!(year %in% mask_years)]
# dt_test   <- dt_y_dt[ year %in% mask_years]
dt_y_eval <- dt_y %>%
  mutate(
    is_holdout = year %in% mask_years,
    e9_obs     = e9,
    e9         = ifelse(is_holdout, NA, e9)  # hold-out 연도는 미관측 처리
  )

dt_y_eval_rates <- dt_y_eval %>%
  mutate(
    e9_rate = (e9_obs / population_total) * 1e5,
    log_rate = log1p(e9_rate)
  )

train_years <- dt_y_eval_rates %>% filter(!is_holdout)
test_years  <- dt_y_eval_rates %>% filter(is_holdout)

calc_metrics <- function(obs, pred) {
  tibble(
    rmse = sqrt(mean((obs - pred)^2, na.rm = TRUE)),
    mae  = mean(abs(obs - pred), na.rm = TRUE),
    mape = mean(abs(obs - pred) / pmax(obs, 1), na.rm = TRUE)
  )
}

# 1) OLS (연도 고정효과) → 로그비율 예측 후 카운트로 환산
ols_holdout <- lm(
  log_rate ~ sex_ratio + pop_65plus_z + trade_balance_z + factor(year),
  data = train_years
)

ols_pred_log <- predict(ols_holdout, newdata = test_years)
ols_pred_cnt <- (exp(ols_pred_log) - 1) * test_years$population_total / 1e5

# 2) SAR (lagsarlm) → 로그비율 예측 후 카운트로 환산
W_mat_eval <- INLA:::inla.graph2matrix(G)
listw_eval <- spdep::mat2listw(as.matrix(W_mat_eval), style = "W")

sar_holdout <- spatialreg::lagsarlm(
  log_rate ~ sex_ratio + pop_65plus_z + trade_balance_z,
  data  = train_years,
  listw = listw_eval,
  method = "eigen"
)

sar_pred_log <- predict(sar_holdout, newdata = test_years, listw = listw_eval)
sar_pred_cnt <- (exp(sar_pred_log) - 1) * test_years$population_total / 1e5

# 3) Bayesian Poisson + BYM2 + AR1 (공변량 없음, hold-out 연도 미관측)
fit_y_ar1_hold <- inla(
  formula = form_y_ar1_nocov,
  data    = dt_y_eval,
  family  = "poisson",
  E       = dt_y_eval$population_total,
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(link = 1, compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                           int.strategy = "auto",
                           control.vb = list(emergency = 50))
)

ar1_pred_cnt <- fit_y_ar1_hold$summary.fitted.values$mean[dt_y_eval$is_holdout]

# 4) Bayesian Poisson + BYM2 + RW1 (공변량 없음, hold-out 연도 미관측)
fit_y_rw1_hold <- inla(
  formula = form_y_rw1_nocov,
  data    = dt_y_eval,
  family  = "poisson",
  E       = dt_y_eval$population_total,
  control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
  control.predictor = list(link = 1, compute = TRUE),
  control.inla      = list(strategy = "simplified.laplace",
                           int.strategy = "auto",
                           control.vb = list(emergency = 50))
)

rw1_pred_cnt <- fit_y_rw1_hold$summary.fitted.values$mean[dt_y_eval$is_holdout]

# hold-out 평가 지표 비교
obs_cnt <- test_years$e9_obs

bind_rows(
  calc_metrics(obs_cnt, ols_pred_cnt)  %>% mutate(model = "OLS (log_rate)"),
  calc_metrics(obs_cnt, sar_pred_cnt)  %>% mutate(model = "SAR (log_rate)"),
  calc_metrics(obs_cnt, ar1_pred_cnt)  %>% mutate(model = "BYM2 + AR1 (no cov)"),
  calc_metrics(obs_cnt, rw1_pred_cnt)  %>% mutate(model = "BYM2 + RW1 (no cov)")
) %>%
  relocate(model)
```



## Sido + Sigungu

```{r}
# form_cov_sido_q <- update(form_interaction, . ~ . + 
#                        trade_export_val_z +
#                        ind_ratio_manufacturing_z +
#                        mig_net_z +
#                        sido_lf_unemployment_rate_z +
#                        sido_num_shortage_z +
#     f(sgg_id,
#       model = "iid",
#       hyper = list(
#         prec = list(prior = "pc.prec", param = c(1, 0.01))
#       )
#     ) +
#     f(sido_id,
#       model = "iid",
#       hyper = list(
#         prec = list(prior = "pc.prec", param = c(1, 0.01))
#       )
#     )
# )
# 
# # 6) INLA 적합 -------------------------------------------------------
# fit_cov_sido_q <- inla(
#   formula = form_cov_sido_q,
#   data    = dt_q,
#   family  = "poisson",
#   E       = dt_q$E_pop,   # 인구를 기대노출로 사용
# 
#   control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
#   control.predictor = list(link = 1, compute = TRUE),
#   control.inla      = list(
#     strategy   = "simplified.laplace",
#     control.vb = list(emergency = 50)
#   )
# )
# 
# # 7) 결과 확인 -------------------------------------------------------
# summary(fit_cov_sido_q)
# fit_cov_sido_q$waic$waic
# fit_cov_sido_q$dic$dic

```

```{r}
# # (선택) 전역 시간 효과를 따로 둘 거면 유지, 아니면 빼도 됨
# form_bym2rw_main <- e9 ~ 1 +
#   lnx + lnm + ln_gdp_pc +
#   sido_consumer_goods_z + sido_capital_goods_z +
#   
#   # 전역 시간 효과
#   f(
#     time_id,
#     model       = "rw1",
#     scale.model = TRUE,
#     hyper       = list(
#       prec = list(prior = "pc.prec", param = c(1, 0.01))
#     )
#   ) +
# 
#   # 시군구×시간 BYM2⊗RW1 (상호작용)
#   f(
#     sgg_id,
#     model       = "bym2",
#     graph       = G,
#     group       = time_id,      # ★ group = time
#     control.group = list(
#       model       = "rw1",
#       scale.model = TRUE,
#       hyper       = list(
#         prec = list(prior = "pc.prec", param = c(1, 0.01))
#       )
#     ),
#     scale.model = TRUE,
#     hyper       = list(
#       prec = list(prior = "pc.prec", param = c(0.5, 0.01)),
#       phi  = list(prior = "pc",       param = c(0.5, 2/3))
#     )
#   ) +
#   
#   # (원하면) 시도 iid 효과 추가
#   f(
#     sido_id,
#     model = "iid",
#     hyper = list(
#       prec = list(prior = "pc.prec", param = c(1, 0.01))
#     )
#   )
# 
# fit_bym2rw_main <- inla(
#   formula = form_bym2rw_main,
#   data    = dt_q,
#   family  = "poisson",
#   E       = dt_q$E_pop,
#   control.compute   = list(dic = TRUE, waic = TRUE, cpo = TRUE),
#   control.predictor = list(link = 1, compute = TRUE),
#   control.inla      = list(
#     strategy   = "simplified.laplace",
#     control.vb = list(emergency = 50)
#   )
# )
# 
# summary(fit_bym2rw_main)
# fit_bym2rw_main$waic$waic
# fit_bym2rw_main$dic$dic
```


## Result

```{r}
library(dplyr)
library(sf)
library(ggplot2)

# 1) RR = exp(eta)
# INLA에서 E= 사용하면 predictor(eta)는 log(RR) 이므로 exp(eta)가 RR
dt_q$RR_mean <- exp(fit_cov_q_sppl$summary.fitted.values[, "mean"])

# 2) time_id -> 연/분기 라벨 (2013Q1부터 시작한다고 가정)
dt_q <- dt_q %>%
  mutate(
    year    = 2013 + (time_id - 1) %/% 4,
    quarter = (time_id - 1) %% 4 + 1,
    tq_lab  = factor(sprintf("%dQ%d", year, quarter),
                     levels = unique(sprintf("%dQ%d", year, quarter)))  # 정렬 유지
  )

sgg_panel <- sgg %>%
  left_join(
    dt_q %>%
      select(space_id, time_id, year, tq_lab, RR_mean),
    by = c("idx" = "space_id")   # ★ 여기서 idx ↔ space_id 매칭
  )

# 연도 평균 RR
sgg_year <- sgg_panel %>%
  st_drop_geometry() %>%
  group_by(idx, year) %>%                             # ★ idx 기준으로 연도 평균
  summarise(RR_year = mean(RR_mean, na.rm = TRUE), .groups = "drop") %>%
  left_join(
    sgg,
    by = "idx"
  ) %>%
  st_as_sf()
```

```{r}
library(scales)

## 1. RR 범위 / 대칭 스케일 만들기 ---------------------------------------
rr_range <- range(sgg_year$RR_year, na.rm = TRUE)
max_dev  <- max(abs(rr_range - 1))
lims     <- 1 + c(-max_dev, max_dev)   # 1을 기준으로 좌우 대칭

## 2. Moraga 스타일 연도별 RR 맵 -----------------------------------------
p_rr_year <- ggplot(sgg_year) +
  geom_sf(aes(fill = RR_year),
          colour = "grey60", linewidth = 0.15) +
  facet_wrap(~ year, ncol = 4) +
  scale_fill_gradient2(
    name = "RR",
    low  = "#5e3c99",   # 보라
    mid  = "white",
    high = "#e66101",   # 주황/빨강
    midpoint = 1,
    limits   = lims,
    oob      = squish
  ) +
  coord_sf(datum = NA) +
  labs(title = "E-9 Relative Risk by SGG, yearly mean") +
  theme_void(base_size = 11) +
  theme(
    # 패널 테두리 + 스트립 (Moraga 느낌)
    panel.border     = element_rect(colour = "grey50", fill = NA, linewidth = 0.3),
    strip.background = element_rect(fill = "grey85", colour = "grey40", linewidth = 0.4),
    strip.text       = element_text(face = "bold", size = 11),

    # 패널 간격 / 여백
    panel.spacing = unit(0.4, "lines"),
    plot.margin   = margin(t = 10, r = 20, b = 10, l = 10),

    # 제목 / 범례
    plot.title      = element_text(size = 18, face = "bold", hjust = 0, margin = margin(b = 10)),
    legend.title    = element_text(size = 11),
    legend.text     = element_text(size = 10),
    legend.key.height = unit(1.4, "lines"),
    legend.key.width  = unit(0.6, "lines")
  )

p_rr_year

```

```{r}
out_dir <- "/Users/kjh/Documents/geostat3_e9/plots"
dir.create(out_dir, showWarnings = FALSE)

ggsave(
  filename = file.path(out_dir, "e9_rr_yearly_mean.png"),
  plot     = p_rr_year,
  width    = 9,     # inch
  height   = 6,
  dpi      = 300
)

```